kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main

steps:
  - name: deploy
    image: appleboy/drone-git-push
    settings:
      remote: ssh://dave@summer.djm.me//home/www/ref.djm.me/repo
      ssh_key:
        from_secret: ssh_private_key
      branch: ${DRONE_COMMIT_BRANCH}
      force: true

  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://matrix.org
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
      template: >
        {{#success build.status}}
          **Build {{build.number}} succeeded** for `{{repo.owner}}/{{repo.name}}` (commit `{{truncate build.commit 8}}` on {{ build.branch }}) - {{build.link}}
        {{else}}
          **WARNING: Build {{build.number}} FAILED** for `{{repo.owner}}/{{repo.name}}` (commit `{{truncate build.commit 8}}` on {{ build.branch }}) - {{build.link}}
        {{/success}}
    when:
      status: [success, failure]
